"""init

Revision ID: 008392bc4cae
Revises: 993fd656eaca
Create Date: 2023-10-29 22:03:46.095265

"""

# revision identifiers, used by Alembic.
revision = '008392bc4cae'
down_revision = '993fd656eaca'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
