"""init

Revision ID: 01cb9e2b864a
Revises: 30061563ad1f
Create Date: 2023-10-29 23:07:07.734197

"""

# revision identifiers, used by Alembic.
revision = '01cb9e2b864a'
down_revision = '30061563ad1f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
