"""init

Revision ID: 02cb2ad26f2a
Revises: 6b78a06ed089
Create Date: 2023-10-29 23:25:37.338079

"""

# revision identifiers, used by Alembic.
revision = '02cb2ad26f2a'
down_revision = '6b78a06ed089'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
