"""init

Revision ID: 096645e54d0b
Revises: 6bf3f007b203
Create Date: 2023-10-29 19:47:09.137847

"""

# revision identifiers, used by Alembic.
revision = '096645e54d0b'
down_revision = '6bf3f007b203'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
