"""init

Revision ID: 0a07e79d8c33
Revises: 85000b7a3f06
Create Date: 2023-10-30 00:27:36.064517

"""

# revision identifiers, used by Alembic.
revision = '0a07e79d8c33'
down_revision = '85000b7a3f06'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
