"""init

Revision ID: 0ecd8bfcb2e8
Revises: f50e24895f05
Create Date: 2023-10-29 21:32:56.951608

"""

# revision identifiers, used by Alembic.
revision = '0ecd8bfcb2e8'
down_revision = 'f50e24895f05'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
