"""init

Revision ID: 0eea80fb8163
Revises: 7ceaa32420df
Create Date: 2023-10-30 07:48:14.408274

"""

# revision identifiers, used by Alembic.
revision = '0eea80fb8163'
down_revision = '7ceaa32420df'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
