"""init

Revision ID: 0fac7079b3fa
Revises: 5f7d4b7cf85c
Create Date: 2023-10-29 23:21:42.917227

"""

# revision identifiers, used by Alembic.
revision = '0fac7079b3fa'
down_revision = '5f7d4b7cf85c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
