"""init

Revision ID: 12c5a05095e6
Revises: 95d2e4fec3a0
Create Date: 2023-10-30 00:38:29.352488

"""

# revision identifiers, used by Alembic.
revision = '12c5a05095e6'
down_revision = '95d2e4fec3a0'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
