"""init

Revision ID: 14ee99a4d12f
Revises: 904e6dff8e85
Create Date: 2023-10-29 23:47:02.031498

"""

# revision identifiers, used by Alembic.
revision = '14ee99a4d12f'
down_revision = '904e6dff8e85'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
