"""init

Revision ID: 18c7e73f9754
Revises: a4e48749a8e4
Create Date: 2023-10-30 09:52:26.102575

"""

# revision identifiers, used by Alembic.
revision = '18c7e73f9754'
down_revision = 'a4e48749a8e4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
