"""init

Revision ID: 19015bcd2621
Revises: 228be8a67c5a
Create Date: 2023-10-30 07:16:47.878831

"""

# revision identifiers, used by Alembic.
revision = '19015bcd2621'
down_revision = '228be8a67c5a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
