"""init

Revision ID: 1917573dc922
Revises: 69a3135e4c9f
Create Date: 2023-10-29 22:19:15.785739

"""

# revision identifiers, used by Alembic.
revision = '1917573dc922'
down_revision = '69a3135e4c9f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
