"""init

Revision ID: 1dc976e3432a
Revises: 5597c104a732
Create Date: 2023-10-29 21:27:35.369193

"""

# revision identifiers, used by Alembic.
revision = '1dc976e3432a'
down_revision = '5597c104a732'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
