"""init

Revision ID: 2000d27e635d
Revises: 4cf04ea2c250
Create Date: 2023-10-29 23:27:58.733859

"""

# revision identifiers, used by Alembic.
revision = '2000d27e635d'
down_revision = '4cf04ea2c250'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
