"""init

Revision ID: 228be8a67c5a
Revises: daec936080a5
Create Date: 2023-10-30 07:15:55.339665

"""

# revision identifiers, used by Alembic.
revision = '228be8a67c5a'
down_revision = 'daec936080a5'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
