"""init

Revision ID: 22e403463f00
Revises: 740b52e9aef6
Create Date: 2023-10-30 00:21:09.465330

"""

# revision identifiers, used by Alembic.
revision = '22e403463f00'
down_revision = '740b52e9aef6'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
