"""init

Revision ID: 2618645b3b35
Revises: abaa511970cd
Create Date: 2023-10-29 23:34:10.419518

"""

# revision identifiers, used by Alembic.
revision = '2618645b3b35'
down_revision = 'abaa511970cd'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
