"""init

Revision ID: 269c71e75b72
Revises: 0fac7079b3fa
Create Date: 2023-10-29 23:23:17.566276

"""

# revision identifiers, used by Alembic.
revision = '269c71e75b72'
down_revision = '0fac7079b3fa'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
