"""init

Revision ID: 2a6d4b4a3313
Revises: d76e104db928
Create Date: 2023-10-29 21:57:36.148241

"""

# revision identifiers, used by Alembic.
revision = '2a6d4b4a3313'
down_revision = 'd76e104db928'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
