"""init

Revision ID: 2c01bbcbc989
Revises: 12c5a05095e6
Create Date: 2023-10-30 00:41:03.945397

"""

# revision identifiers, used by Alembic.
revision = '2c01bbcbc989'
down_revision = '12c5a05095e6'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
