"""init

Revision ID: 307c3da1cd9d
Revises: 684aa9cc270e
Create Date: 2023-10-30 07:43:27.648435

"""

# revision identifiers, used by Alembic.
revision = '307c3da1cd9d'
down_revision = '684aa9cc270e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
