"""init

Revision ID: 329e168f4223
Revises: 01cb9e2b864a
Create Date: 2023-10-29 23:12:35.751897

"""

# revision identifiers, used by Alembic.
revision = '329e168f4223'
down_revision = '01cb9e2b864a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
