"""init

Revision ID: 34ad7192c3b0
Revises: 9a0f1dbd2d6e
Create Date: 2023-10-29 20:03:29.514358

"""

# revision identifiers, used by Alembic.
revision = '34ad7192c3b0'
down_revision = '9a0f1dbd2d6e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
