"""init

Revision ID: 34bc297ea4de
Revises: 008392bc4cae
Create Date: 2023-10-29 22:06:20.655816

"""

# revision identifiers, used by Alembic.
revision = '34bc297ea4de'
down_revision = '008392bc4cae'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
