"""init

Revision ID: 38ce1ae8010c
Revises: 40ba17deb7eb
Create Date: 2023-10-29 21:49:21.362550

"""

# revision identifiers, used by Alembic.
revision = '38ce1ae8010c'
down_revision = '40ba17deb7eb'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
