"""init

Revision ID: 3c0d55515530
Revises: 329e168f4223
Create Date: 2023-10-29 23:15:11.143065

"""

# revision identifiers, used by Alembic.
revision = '3c0d55515530'
down_revision = '329e168f4223'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
