"""init

Revision ID: 3c5e7b45e501
Revises: ade327b0a387
Create Date: 2023-10-29 23:37:28.227051

"""

# revision identifiers, used by Alembic.
revision = '3c5e7b45e501'
down_revision = 'ade327b0a387'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
