"""init

Revision ID: 40ba17deb7eb
Revises: d310e436e900
Create Date: 2023-10-29 21:44:25.896734

"""

# revision identifiers, used by Alembic.
revision = '40ba17deb7eb'
down_revision = 'd310e436e900'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
