"""init

Revision ID: 4258b4728898
Revises: 22e403463f00
Create Date: 2023-10-30 00:25:44.454469

"""

# revision identifiers, used by Alembic.
revision = '4258b4728898'
down_revision = '22e403463f00'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
