"""init

Revision ID: 43b46090177c
Revises: c7512c72c8ad
Create Date: 2023-10-30 09:12:08.338645

"""

# revision identifiers, used by Alembic.
revision = '43b46090177c'
down_revision = 'c7512c72c8ad'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
