"""init

Revision ID: 4a935beb6d87
Revises: 0eea80fb8163
Create Date: 2023-10-30 08:07:13.150307

"""

# revision identifiers, used by Alembic.
revision = '4a935beb6d87'
down_revision = '0eea80fb8163'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
