"""init

Revision ID: 4ea06e8967c7
Revises: 1917573dc922
Create Date: 2023-10-29 22:23:28.597583

"""

# revision identifiers, used by Alembic.
revision = '4ea06e8967c7'
down_revision = '1917573dc922'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
