"""init

Revision ID: 4f86f59f34ed
Revises: 2000d27e635d
Create Date: 2023-10-29 23:29:49.852776

"""

# revision identifiers, used by Alembic.
revision = '4f86f59f34ed'
down_revision = '2000d27e635d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
