"""init

Revision ID: 510e188adb80
Revises: 8deaf7f45e54
Create Date: 2023-10-30 08:21:55.005678

"""

# revision identifiers, used by Alembic.
revision = '510e188adb80'
down_revision = '8deaf7f45e54'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
