"""init

Revision ID: 51ac8b2fd34f
Revises: 2a6d4b4a3313
Create Date: 2023-10-29 21:58:31.067872

"""

# revision identifiers, used by Alembic.
revision = '51ac8b2fd34f'
down_revision = '2a6d4b4a3313'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
