"""init

Revision ID: 5597c104a732
Revises: bdfdb793b13a
Create Date: 2023-10-29 21:25:13.181347

"""

# revision identifiers, used by Alembic.
revision = '5597c104a732'
down_revision = 'bdfdb793b13a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
