"""init

Revision ID: 5d9ad13892e4
Revises: afd906e8a574
Create Date: 2023-10-29 23:41:18.842038

"""

# revision identifiers, used by Alembic.
revision = '5d9ad13892e4'
down_revision = 'afd906e8a574'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
