"""init

Revision ID: 5f735263d8e6
Revises: 19015bcd2621
Create Date: 2023-10-30 07:23:00.612505

"""

# revision identifiers, used by Alembic.
revision = '5f735263d8e6'
down_revision = '19015bcd2621'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
