"""init

Revision ID: 5f7d4b7cf85c
Revises: ebdc78c5349b
Create Date: 2023-10-29 23:20:56.264978

"""

# revision identifiers, used by Alembic.
revision = '5f7d4b7cf85c'
down_revision = 'ebdc78c5349b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
