"""init

Revision ID: 6207da49313c
Revises: ddc854fcfba7
Create Date: 2023-10-29 22:28:07.735631

"""

# revision identifiers, used by Alembic.
revision = '6207da49313c'
down_revision = 'ddc854fcfba7'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
