"""init

Revision ID: 684aa9cc270e
Revises: 5f735263d8e6
Create Date: 2023-10-30 07:26:44.628246

"""

# revision identifiers, used by Alembic.
revision = '684aa9cc270e'
down_revision = '5f735263d8e6'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
