"""init

Revision ID: 69a3135e4c9f
Revises: ed4b8ed2c6d8
Create Date: 2023-10-29 22:18:17.702865

"""

# revision identifiers, used by Alembic.
revision = '69a3135e4c9f'
down_revision = 'ed4b8ed2c6d8'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
