"""init

Revision ID: 6a848eb13a37
Revises: 510e188adb80
Create Date: 2023-10-30 08:36:14.707398

"""

# revision identifiers, used by Alembic.
revision = '6a848eb13a37'
down_revision = '510e188adb80'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
