"""init

Revision ID: 6b392b4c25d1
Revises: 6d3e1bd7b7fa
Create Date: 2023-10-29 18:36:28.658958

"""

# revision identifiers, used by Alembic.
revision = '6b392b4c25d1'
down_revision = '6d3e1bd7b7fa'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
