"""init

Revision ID: 6b78a06ed089
Revises: 9b2a63551f82
Create Date: 2023-10-29 23:24:15.046279

"""

# revision identifiers, used by Alembic.
revision = '6b78a06ed089'
down_revision = '9b2a63551f82'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
