"""init

Revision ID: 6bf3f007b203
Revises: a395f96fe3b4
Create Date: 2023-10-29 19:44:53.629530

"""

# revision identifiers, used by Alembic.
revision = '6bf3f007b203'
down_revision = 'a395f96fe3b4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
