"""init

Revision ID: 6d3e1bd7b7fa
Revises: dd33cb03d01f
Create Date: 2023-10-29 18:33:32.946621

"""

# revision identifiers, used by Alembic.
revision = '6d3e1bd7b7fa'
down_revision = 'dd33cb03d01f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
