"""init

Revision ID: 740b52e9aef6
Revises: 0e19bd458dd6
Create Date: 2023-10-30 00:19:48.298791

"""

# revision identifiers, used by Alembic.
revision = '740b52e9aef6'
down_revision = '0e19bd458dd6'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
