"""init

Revision ID: 7c9b2f66b9d3
Revises: b2a03f30ce3f
Create Date: 2023-10-29 20:10:14.225465

"""

# revision identifiers, used by Alembic.
revision = '7c9b2f66b9d3'
down_revision = 'b2a03f30ce3f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
