"""init

Revision ID: 7ceaa32420df
Revises: 307c3da1cd9d
Create Date: 2023-10-30 07:44:59.830023

"""

# revision identifiers, used by Alembic.
revision = '7ceaa32420df'
down_revision = '307c3da1cd9d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
