"""init

Revision ID: 809442fbc09e
Revises: bc44d6d74b64
Create Date: 2023-10-29 21:51:08.012766

"""

# revision identifiers, used by Alembic.
revision = '809442fbc09e'
down_revision = 'bc44d6d74b64'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
