"""init

Revision ID: 82f71b00da3b
Revises: 8450738c83a0
Create Date: 2023-10-30 09:27:58.523266

"""

# revision identifiers, used by Alembic.
revision = '82f71b00da3b'
down_revision = '8450738c83a0'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
