"""init

Revision ID: 8450738c83a0
Revises: 8f786c447c6f
Create Date: 2023-10-30 09:23:52.807012

"""

# revision identifiers, used by Alembic.
revision = '8450738c83a0'
down_revision = '8f786c447c6f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
