"""init

Revision ID: 85000b7a3f06
Revises: 4258b4728898
Create Date: 2023-10-30 00:26:08.046256

"""

# revision identifiers, used by Alembic.
revision = '85000b7a3f06'
down_revision = '4258b4728898'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
