"""init

Revision ID: 86e844cdb0d1
Revises: 93fb73b8a33d
Create Date: 2023-10-29 22:44:53.929402

"""

# revision identifiers, used by Alembic.
revision = '86e844cdb0d1'
down_revision = '93fb73b8a33d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
