"""init

Revision ID: 8deaf7f45e54
Revises: 4a935beb6d87
Create Date: 2023-10-30 08:18:02.287597

"""

# revision identifiers, used by Alembic.
revision = '8deaf7f45e54'
down_revision = '4a935beb6d87'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
