"""init

Revision ID: 8f786c447c6f
Revises: 43b46090177c
Create Date: 2023-10-30 09:18:18.543632

"""

# revision identifiers, used by Alembic.
revision = '8f786c447c6f'
down_revision = '43b46090177c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
