"""init

Revision ID: 8fd532471601
Revises: 4ea06e8967c7
Create Date: 2023-10-29 22:24:23.900912

"""

# revision identifiers, used by Alembic.
revision = '8fd532471601'
down_revision = '4ea06e8967c7'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
