"""init

Revision ID: 904e6dff8e85
Revises: 00817c8ad8d4
Create Date: 2023-10-29 23:44:33.387640

"""

# revision identifiers, used by Alembic.
revision = '904e6dff8e85'
down_revision = '00817c8ad8d4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
