"""init

Revision ID: 93fb73b8a33d
Revises: e953cfb798e4
Create Date: 2023-10-29 22:41:26.458249

"""

# revision identifiers, used by Alembic.
revision = '93fb73b8a33d'
down_revision = 'e953cfb798e4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
