"""init

Revision ID: 9442a7690093
Revises: 99b00458df5f
Create Date: 2023-10-29 22:51:20.470065

"""

# revision identifiers, used by Alembic.
revision = '9442a7690093'
down_revision = '99b00458df5f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
