"""init

Revision ID: 95d2e4fec3a0
Revises: 0a07e79d8c33
Create Date: 2023-10-30 00:29:05.683769

"""

# revision identifiers, used by Alembic.
revision = '95d2e4fec3a0'
down_revision = '0a07e79d8c33'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
