"""init

Revision ID: 993fd656eaca
Revises: a813240cdfa4
Create Date: 2023-10-29 22:02:38.029269

"""

# revision identifiers, used by Alembic.
revision = '993fd656eaca'
down_revision = 'a813240cdfa4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
