"""init

Revision ID: 99b00458df5f
Revises: cfb2f54ef5db
Create Date: 2023-10-29 22:50:06.053509

"""

# revision identifiers, used by Alembic.
revision = '99b00458df5f'
down_revision = 'cfb2f54ef5db'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
