"""init

Revision ID: 9a0f1dbd2d6e
Revises: 096645e54d0b
Create Date: 2023-10-29 19:48:14.426921

"""

# revision identifiers, used by Alembic.
revision = '9a0f1dbd2d6e'
down_revision = '096645e54d0b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
