"""init

Revision ID: 9a6b9810a52f
Revises: 6207da49313c
Create Date: 2023-10-29 22:29:55.798448

"""

# revision identifiers, used by Alembic.
revision = '9a6b9810a52f'
down_revision = '6207da49313c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
