"""init

Revision ID: 9b2a63551f82
Revises: 269c71e75b72
Create Date: 2023-10-29 23:23:45.892182

"""

# revision identifiers, used by Alembic.
revision = '9b2a63551f82'
down_revision = '269c71e75b72'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
