"""init

Revision ID: 9d1503d93954
Revises: c16ee908cb06
Create Date: 2023-10-30 00:05:55.435998

"""

# revision identifiers, used by Alembic.
revision = '9d1503d93954'
down_revision = 'c16ee908cb06'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
