"""init

Revision ID: a395f96fe3b4
Revises: 6b392b4c25d1
Create Date: 2023-10-29 18:41:25.832200

"""

# revision identifiers, used by Alembic.
revision = 'a395f96fe3b4'
down_revision = '6b392b4c25d1'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
