"""init

Revision ID: a4e48749a8e4
Revises: 82f71b00da3b
Create Date: 2023-10-30 09:46:12.683252

"""

# revision identifiers, used by Alembic.
revision = 'a4e48749a8e4'
down_revision = '82f71b00da3b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
