"""init

Revision ID: a813240cdfa4
Revises: ccb8e5ce0298
Create Date: 2023-10-29 22:01:52.360436

"""

# revision identifiers, used by Alembic.
revision = 'a813240cdfa4'
down_revision = 'ccb8e5ce0298'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
