"""init

Revision ID: abaa511970cd
Revises: 4f86f59f34ed
Create Date: 2023-10-29 23:32:36.321771

"""

# revision identifiers, used by Alembic.
revision = 'abaa511970cd'
down_revision = '4f86f59f34ed'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
