"""init

Revision ID: ade327b0a387
Revises: 2618645b3b35
Create Date: 2023-10-29 23:35:12.670227

"""

# revision identifiers, used by Alembic.
revision = 'ade327b0a387'
down_revision = '2618645b3b35'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
