"""init

Revision ID: afd906e8a574
Revises: 3c5e7b45e501
Create Date: 2023-10-29 23:39:11.773744

"""

# revision identifiers, used by Alembic.
revision = 'afd906e8a574'
down_revision = '3c5e7b45e501'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
