"""init

Revision ID: b2a03f30ce3f
Revises: 34ad7192c3b0
Create Date: 2023-10-29 20:09:28.027213

"""

# revision identifiers, used by Alembic.
revision = 'b2a03f30ce3f'
down_revision = '34ad7192c3b0'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
