"""init

Revision ID: bc44d6d74b64
Revises: 38ce1ae8010c
Create Date: 2023-10-29 21:50:11.467413

"""

# revision identifiers, used by Alembic.
revision = 'bc44d6d74b64'
down_revision = '38ce1ae8010c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
