"""init

Revision ID: bda83d0f513a
Revises: d84ba17caa8a
Create Date: 2023-10-29 22:37:24.130620

"""

# revision identifiers, used by Alembic.
revision = 'bda83d0f513a'
down_revision = 'd84ba17caa8a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
