"""init

Revision ID: bdfdb793b13a
Revises: 7c9b2f66b9d3
Create Date: 2023-10-29 21:21:08.206953

"""

# revision identifiers, used by Alembic.
revision = 'bdfdb793b13a'
down_revision = '7c9b2f66b9d3'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
