"""init

Revision ID: c00d45f5c98a
Revises: d17dc2be86ad
Create Date: 2023-10-29 21:41:02.779085

"""

# revision identifiers, used by Alembic.
revision = 'c00d45f5c98a'
down_revision = 'd17dc2be86ad'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
