"""init

Revision ID: c16ee908cb06
Revises: 14ee99a4d12f
Create Date: 2023-10-29 23:50:09.770310

"""

# revision identifiers, used by Alembic.
revision = 'c16ee908cb06'
down_revision = '14ee99a4d12f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
