"""init

Revision ID: c3c7067afc63
Revises: 9a6b9810a52f
Create Date: 2023-10-29 22:31:59.980575

"""

# revision identifiers, used by Alembic.
revision = 'c3c7067afc63'
down_revision = '9a6b9810a52f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
