"""init

Revision ID: c7512c72c8ad
Revises: edc431c9898b
Create Date: 2023-10-30 09:04:40.773330

"""

# revision identifiers, used by Alembic.
revision = 'c7512c72c8ad'
down_revision = 'edc431c9898b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
