"""init

Revision ID: c87ca116fc21
Revises: d3eb4694205d
Create Date: 2023-10-29 21:55:36.818310

"""

# revision identifiers, used by Alembic.
revision = 'c87ca116fc21'
down_revision = 'd3eb4694205d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
