"""init

Revision ID: ccb8e5ce0298
Revises: f3b1941bab99
Create Date: 2023-10-29 22:00:38.490416

"""

# revision identifiers, used by Alembic.
revision = 'ccb8e5ce0298'
down_revision = 'f3b1941bab99'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
