"""init

Revision ID: cfb2f54ef5db
Revises: 86e844cdb0d1
Create Date: 2023-10-29 22:46:53.028809

"""

# revision identifiers, used by Alembic.
revision = 'cfb2f54ef5db'
down_revision = '86e844cdb0d1'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
