"""init

Revision ID: d29f88febb71
Revises: 3c0d55515530
Create Date: 2023-10-29 23:17:50.414472

"""

# revision identifiers, used by Alembic.
revision = 'd29f88febb71'
down_revision = '3c0d55515530'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
