"""init

Revision ID: d310e436e900
Revises: c00d45f5c98a
Create Date: 2023-10-29 21:43:11.154852

"""

# revision identifiers, used by Alembic.
revision = 'd310e436e900'
down_revision = 'c00d45f5c98a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
