"""init

Revision ID: d3eb4694205d
Revises: 809442fbc09e
Create Date: 2023-10-29 21:52:06.110296

"""

# revision identifiers, used by Alembic.
revision = 'd3eb4694205d'
down_revision = '809442fbc09e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
