"""init

Revision ID: d76e104db928
Revises: c87ca116fc21
Create Date: 2023-10-29 21:56:47.006949

"""

# revision identifiers, used by Alembic.
revision = 'd76e104db928'
down_revision = 'c87ca116fc21'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
