"""init

Revision ID: d84ba17caa8a
Revises: c3c7067afc63
Create Date: 2023-10-29 22:33:19.008996

"""

# revision identifiers, used by Alembic.
revision = 'd84ba17caa8a'
down_revision = 'c3c7067afc63'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
