"""init

Revision ID: daec936080a5
Revises: 2c01bbcbc989
Create Date: 2023-10-30 07:09:36.624244

"""

# revision identifiers, used by Alembic.
revision = 'daec936080a5'
down_revision = '2c01bbcbc989'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
