"""init

Revision ID: ddc854fcfba7
Revises: 8fd532471601
Create Date: 2023-10-29 22:27:36.945206

"""

# revision identifiers, used by Alembic.
revision = 'ddc854fcfba7'
down_revision = '8fd532471601'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
