"""init

Revision ID: e700bfd537b6
Revises: f6ebca9c975d
Create Date: 2023-10-29 22:09:43.581907

"""

# revision identifiers, used by Alembic.
revision = 'e700bfd537b6'
down_revision = 'f6ebca9c975d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
