"""init

Revision ID: e953cfb798e4
Revises: bda83d0f513a
Create Date: 2023-10-29 22:39:35.189928

"""

# revision identifiers, used by Alembic.
revision = 'e953cfb798e4'
down_revision = 'bda83d0f513a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
