"""init

Revision ID: ebdc78c5349b
Revises: d29f88febb71
Create Date: 2023-10-29 23:18:51.789150

"""

# revision identifiers, used by Alembic.
revision = 'ebdc78c5349b'
down_revision = 'd29f88febb71'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
