"""init

Revision ID: ed4b8ed2c6d8
Revises: b6269a734716
Create Date: 2023-10-29 22:15:35.341465

"""

# revision identifiers, used by Alembic.
revision = 'ed4b8ed2c6d8'
down_revision = 'b6269a734716'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
