"""init

Revision ID: f07b768e1fc6
Revises: 9442a7690093
Create Date: 2023-10-29 23:02:42.221745

"""

# revision identifiers, used by Alembic.
revision = 'f07b768e1fc6'
down_revision = '9442a7690093'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
