"""init

Revision ID: f3b1941bab99
Revises: 51ac8b2fd34f
Create Date: 2023-10-29 21:59:48.683277

"""

# revision identifiers, used by Alembic.
revision = 'f3b1941bab99'
down_revision = '51ac8b2fd34f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
