"""init

Revision ID: f50e24895f05
Revises: 1dc976e3432a
Create Date: 2023-10-29 21:30:57.083595

"""

# revision identifiers, used by Alembic.
revision = 'f50e24895f05'
down_revision = '1dc976e3432a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
