"""init

Revision ID: f6ebca9c975d
Revises: 34bc297ea4de
Create Date: 2023-10-29 22:07:27.380832

"""

# revision identifiers, used by Alembic.
revision = 'f6ebca9c975d'
down_revision = '34bc297ea4de'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
